-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.student
(
    id integer NOT NULL,
    name character varying NOT NULL,
    surname character varying NOT NULL,
    birth_date date,
    gender boolean,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subject
(
    id integer NOT NULL,
    name character varying NOT NULL,
    credits integer,
    optional boolean,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.teacher
(
    id integer NOT NULL,
    name character varying NOT NULL,
    surname character varying NOT NULL,
    degree character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.curriculum
(
    id integer NOT NULL,
    validity date NOT NULL,
    name character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subject_curriculum
(
    id integer NOT NULL,
    id_subject integer,
    id_curriculum integer,
    semester integer,
    PRIMARY KEY (id_subject)
);

CREATE TABLE IF NOT EXISTS public.course
(
    id integer,
    id_teacher integer,
    id_subject_curriculum integer,
    curricullar_period_end date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.enrollment
(
    id integer NOT NULL,
    id_student integer,
    id_couse integer,
    grade integer,
    PRIMARY KEY (id_couse)
);

ALTER TABLE IF EXISTS public.subject_curriculum
    ADD CONSTRAINT fk_subject FOREIGN KEY (id_subject)
    REFERENCES public.subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.subject_curriculum
    ADD CONSTRAINT fk_curriculum FOREIGN KEY (id_curriculum)
    REFERENCES public.curriculum (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.course
    ADD CONSTRAINT fk_teacher FOREIGN KEY (id_teacher)
    REFERENCES public.teacher (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.course
    ADD CONSTRAINT fk_subject_curriculum FOREIGN KEY (id_subject_curriculum)
    REFERENCES public.subject_curriculum (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT fk_student FOREIGN KEY (id_student)
    REFERENCES public.student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT fk_course FOREIGN KEY (id_couse)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;